/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'orderConfirmed' : IDL.Null,
  'readyForPickup' : IDL.Null,
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'orderReceived' : IDL.Null,
  'paymentVerification' : IDL.Null,
});
export const Centavos = IDL.Nat;
export const CustomerInfo = IDL.Record({
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
});
export const Timestamp = IDL.Nat;
export const OrderType = IDL.Variant({
  'takeOut' : IDL.Null,
  'dineIn' : IDL.Null,
});
export const TakeOutDetails = IDL.Record({ 'pickupTime' : IDL.Text });
export const DineInDetails = IDL.Record({
  'numberOfCustomers' : IDL.Nat,
  'tableNumber' : IDL.Text,
});
export const Id = IDL.Nat;
export const LineCustomization = IDL.Record({
  'sugarLevel' : IDL.Opt(IDL.Text),
  'milkOption' : IDL.Opt(IDL.Text),
  'addOnIds' : IDL.Vec(Id),
  'sizeId' : IDL.Opt(Id),
  'iceLevel' : IDL.Opt(IDL.Text),
});
export const OrderItem = IDL.Record({
  'lineTotal' : Centavos,
  'productId' : Id,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : Centavos,
  'customization' : LineCustomization,
});
export const PaymentMethod = IDL.Variant({
  'cash' : IDL.Null,
  'maya' : IDL.Null,
  'gcash' : IDL.Null,
});
export const FileRef = IDL.Vec(IDL.Nat8);
export const StoredFile = IDL.Record({
  'blob' : FileRef,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
});
export const PaymentInfo = IDL.Record({
  'method' : PaymentMethod,
  'referenceNumber' : IDL.Opt(IDL.Text),
  'proof' : IDL.Opt(StoredFile),
});
export const Order = IDL.Record({
  'status' : OrderStatus,
  'total' : Centavos,
  'customer' : CustomerInfo,
  'createdAt' : Timestamp,
  'orderType' : OrderType,
  'serviceFee' : Centavos,
  'takeOut' : IDL.Opt(TakeOutDetails),
  'updatedAt' : Timestamp,
  'specialInstructions' : IDL.Text,
  'dineIn' : IDL.Opt(DineInDetails),
  'items' : IDL.Vec(OrderItem),
  'orderNumber' : IDL.Text,
  'payment' : PaymentInfo,
  'subtotal' : Centavos,
});
export const OrderError = IDL.Variant({
  'invalidStatusTransition' : IDL.Record({
    'to' : OrderStatus,
    'from' : OrderStatus,
  }),
  'notAuthorized' : IDL.Null,
  'unknownOrder' : IDL.Text,
  'invalidCustomerInfo' : IDL.Text,
  'productUnavailable' : Id,
  'unknownProduct' : Id,
  'invalidOrderType' : IDL.Text,
  'invalidPayment' : IDL.Text,
  'emptyCart' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : Order, 'err' : OrderError });
export const AddOnInput = IDL.Record({
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'price' : Centavos,
});
export const CategoryInput = IDL.Record({
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
});
export const ProductInput = IDL.Record({
  'categoryId' : Id,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'addOnIds' : IDL.Vec(Id),
  'sizeOptionIds' : IDL.Vec(Id),
  'image' : IDL.Opt(StoredFile),
  'price' : Centavos,
});
export const SizeOptionInput = IDL.Record({
  'surcharge' : Centavos,
  'name' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const CallerRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'anonymous' : IDL.Null,
});
export const DashboardStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'totalSales' : Centavos,
  'todaysSales' : Centavos,
  'completedOrders' : IDL.Nat,
});
export const Category = IDL.Record({
  'id' : Id,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
});
export const SizeOption = IDL.Record({
  'id' : Id,
  'surcharge' : Centavos,
  'name' : IDL.Text,
});
export const AddOn = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'price' : Centavos,
});
export const Product = IDL.Record({
  'id' : Id,
  'categoryId' : Id,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'addOnIds' : IDL.Vec(Id),
  'sizeOptionIds' : IDL.Vec(Id),
  'image' : IDL.Opt(StoredFile),
  'price' : Centavos,
});
export const Menu = IDL.Record({
  'categories' : IDL.Vec(Category),
  'sizes' : IDL.Vec(SizeOption),
  'addOns' : IDL.Vec(AddOn),
  'products' : IDL.Vec(Product),
});
export const PaymentSettings = IDL.Record({
  'mayaNumber' : IDL.Text,
  'gcashQr' : IDL.Opt(StoredFile),
  'gcashNumber' : IDL.Text,
  'mayaQr' : IDL.Opt(StoredFile),
});
export const OrderFilter = IDL.Record({
  'status' : IDL.Opt(OrderStatus),
  'orderType' : IDL.Opt(OrderType),
});
export const OrderSummary = IDL.Record({
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'total' : Centavos,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Timestamp,
  'orderType' : OrderType,
  'orderNumber' : IDL.Text,
});
export const PlaceOrderInput = IDL.Record({
  'customer' : CustomerInfo,
  'orderType' : OrderType,
  'takeOut' : IDL.Opt(TakeOutDetails),
  'specialInstructions' : IDL.Text,
  'dineIn' : IDL.Opt(DineInDetails),
  'items' : IDL.Vec(OrderItem),
  'payment' : PaymentInfo,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : OrderError });
export const PaymentSettingsInput = IDL.Record({
  'mayaNumber' : IDL.Text,
  'gcashQr' : IDL.Opt(StoredFile),
  'gcashNumber' : IDL.Text,
  'mayaQr' : IDL.Opt(StoredFile),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([IDL.Text], [Result], []),
  'createAddOn' : IDL.Func([AddOnInput], [Id], []),
  'createCategory' : IDL.Func([CategoryInput], [Id], []),
  'createProduct' : IDL.Func([ProductInput], [Id], []),
  'createSizeOption' : IDL.Func([SizeOptionInput], [Id], []),
  'deleteAddOn' : IDL.Func([Id], [IDL.Bool], []),
  'deleteCategory' : IDL.Func([Id], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([Id], [IDL.Bool], []),
  'deleteSizeOption' : IDL.Func([Id], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerRole' : IDL.Func([], [CallerRole], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMenu' : IDL.Func([], [Menu], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
  'getProduct' : IDL.Func([Id], [IDL.Opt(Product)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listOrders' : IDL.Func([OrderFilter], [IDL.Vec(OrderSummary)], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderInput], [Result_1], []),
  'registerCustomer' : IDL.Func([], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateAddOn' : IDL.Func([Id, AddOnInput], [IDL.Bool], []),
  'updateCategory' : IDL.Func([Id, CategoryInput], [IDL.Bool], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [Result], []),
  'updatePaymentSettings' : IDL.Func(
      [PaymentSettingsInput],
      [PaymentSettings],
      [],
    ),
  'updateProduct' : IDL.Func([Id, ProductInput], [IDL.Bool], []),
  'updateSizeOption' : IDL.Func([Id, SizeOptionInput], [IDL.Bool], []),
  'verifyPayment' : IDL.Func([IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'orderConfirmed' : IDL.Null,
    'readyForPickup' : IDL.Null,
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'orderReceived' : IDL.Null,
    'paymentVerification' : IDL.Null,
  });
  const Centavos = IDL.Nat;
  const CustomerInfo = IDL.Record({
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
  });
  const Timestamp = IDL.Nat;
  const OrderType = IDL.Variant({ 'takeOut' : IDL.Null, 'dineIn' : IDL.Null });
  const TakeOutDetails = IDL.Record({ 'pickupTime' : IDL.Text });
  const DineInDetails = IDL.Record({
    'numberOfCustomers' : IDL.Nat,
    'tableNumber' : IDL.Text,
  });
  const Id = IDL.Nat;
  const LineCustomization = IDL.Record({
    'sugarLevel' : IDL.Opt(IDL.Text),
    'milkOption' : IDL.Opt(IDL.Text),
    'addOnIds' : IDL.Vec(Id),
    'sizeId' : IDL.Opt(Id),
    'iceLevel' : IDL.Opt(IDL.Text),
  });
  const OrderItem = IDL.Record({
    'lineTotal' : Centavos,
    'productId' : Id,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : Centavos,
    'customization' : LineCustomization,
  });
  const PaymentMethod = IDL.Variant({
    'cash' : IDL.Null,
    'maya' : IDL.Null,
    'gcash' : IDL.Null,
  });
  const FileRef = IDL.Vec(IDL.Nat8);
  const StoredFile = IDL.Record({
    'blob' : FileRef,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const PaymentInfo = IDL.Record({
    'method' : PaymentMethod,
    'referenceNumber' : IDL.Opt(IDL.Text),
    'proof' : IDL.Opt(StoredFile),
  });
  const Order = IDL.Record({
    'status' : OrderStatus,
    'total' : Centavos,
    'customer' : CustomerInfo,
    'createdAt' : Timestamp,
    'orderType' : OrderType,
    'serviceFee' : Centavos,
    'takeOut' : IDL.Opt(TakeOutDetails),
    'updatedAt' : Timestamp,
    'specialInstructions' : IDL.Text,
    'dineIn' : IDL.Opt(DineInDetails),
    'items' : IDL.Vec(OrderItem),
    'orderNumber' : IDL.Text,
    'payment' : PaymentInfo,
    'subtotal' : Centavos,
  });
  const OrderError = IDL.Variant({
    'invalidStatusTransition' : IDL.Record({
      'to' : OrderStatus,
      'from' : OrderStatus,
    }),
    'notAuthorized' : IDL.Null,
    'unknownOrder' : IDL.Text,
    'invalidCustomerInfo' : IDL.Text,
    'productUnavailable' : Id,
    'unknownProduct' : Id,
    'invalidOrderType' : IDL.Text,
    'invalidPayment' : IDL.Text,
    'emptyCart' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : Order, 'err' : OrderError });
  const AddOnInput = IDL.Record({
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'price' : Centavos,
  });
  const CategoryInput = IDL.Record({
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
  });
  const ProductInput = IDL.Record({
    'categoryId' : Id,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'addOnIds' : IDL.Vec(Id),
    'sizeOptionIds' : IDL.Vec(Id),
    'image' : IDL.Opt(StoredFile),
    'price' : Centavos,
  });
  const SizeOptionInput = IDL.Record({
    'surcharge' : Centavos,
    'name' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const CallerRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'anonymous' : IDL.Null,
  });
  const DashboardStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'totalSales' : Centavos,
    'todaysSales' : Centavos,
    'completedOrders' : IDL.Nat,
  });
  const Category = IDL.Record({
    'id' : Id,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
  });
  const SizeOption = IDL.Record({
    'id' : Id,
    'surcharge' : Centavos,
    'name' : IDL.Text,
  });
  const AddOn = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'price' : Centavos,
  });
  const Product = IDL.Record({
    'id' : Id,
    'categoryId' : Id,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'addOnIds' : IDL.Vec(Id),
    'sizeOptionIds' : IDL.Vec(Id),
    'image' : IDL.Opt(StoredFile),
    'price' : Centavos,
  });
  const Menu = IDL.Record({
    'categories' : IDL.Vec(Category),
    'sizes' : IDL.Vec(SizeOption),
    'addOns' : IDL.Vec(AddOn),
    'products' : IDL.Vec(Product),
  });
  const PaymentSettings = IDL.Record({
    'mayaNumber' : IDL.Text,
    'gcashQr' : IDL.Opt(StoredFile),
    'gcashNumber' : IDL.Text,
    'mayaQr' : IDL.Opt(StoredFile),
  });
  const OrderFilter = IDL.Record({
    'status' : IDL.Opt(OrderStatus),
    'orderType' : IDL.Opt(OrderType),
  });
  const OrderSummary = IDL.Record({
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'total' : Centavos,
    'paymentMethod' : PaymentMethod,
    'createdAt' : Timestamp,
    'orderType' : OrderType,
    'orderNumber' : IDL.Text,
  });
  const PlaceOrderInput = IDL.Record({
    'customer' : CustomerInfo,
    'orderType' : OrderType,
    'takeOut' : IDL.Opt(TakeOutDetails),
    'specialInstructions' : IDL.Text,
    'dineIn' : IDL.Opt(DineInDetails),
    'items' : IDL.Vec(OrderItem),
    'payment' : PaymentInfo,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : OrderError });
  const PaymentSettingsInput = IDL.Record({
    'mayaNumber' : IDL.Text,
    'gcashQr' : IDL.Opt(StoredFile),
    'gcashNumber' : IDL.Text,
    'mayaQr' : IDL.Opt(StoredFile),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([IDL.Text], [Result], []),
    'createAddOn' : IDL.Func([AddOnInput], [Id], []),
    'createCategory' : IDL.Func([CategoryInput], [Id], []),
    'createProduct' : IDL.Func([ProductInput], [Id], []),
    'createSizeOption' : IDL.Func([SizeOptionInput], [Id], []),
    'deleteAddOn' : IDL.Func([Id], [IDL.Bool], []),
    'deleteCategory' : IDL.Func([Id], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([Id], [IDL.Bool], []),
    'deleteSizeOption' : IDL.Func([Id], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerRole' : IDL.Func([], [CallerRole], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMenu' : IDL.Func([], [Menu], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
    'getProduct' : IDL.Func([Id], [IDL.Opt(Product)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listOrders' : IDL.Func([OrderFilter], [IDL.Vec(OrderSummary)], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderInput], [Result_1], []),
    'registerCustomer' : IDL.Func([], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateAddOn' : IDL.Func([Id, AddOnInput], [IDL.Bool], []),
    'updateCategory' : IDL.Func([Id, CategoryInput], [IDL.Bool], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [Result], []),
    'updatePaymentSettings' : IDL.Func(
        [PaymentSettingsInput],
        [PaymentSettings],
        [],
      ),
    'updateProduct' : IDL.Func([Id, ProductInput], [IDL.Bool], []),
    'updateSizeOption' : IDL.Func([Id, SizeOptionInput], [IDL.Bool], []),
    'verifyPayment' : IDL.Func([IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };