/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddOn {
  'id' : Id,
  'name' : string,
  'available' : boolean,
  'price' : Centavos,
}
export interface AddOnInput {
  'name' : string,
  'available' : boolean,
  'price' : Centavos,
}
export type CallerRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'anonymous' : null };
export interface Category { 'id' : Id, 'sortOrder' : bigint, 'name' : string }
export interface CategoryInput { 'sortOrder' : bigint, 'name' : string }
export interface Cell { 'value' : Value, 'name' : string }
export type Centavos = bigint;
export interface CustomerInfo {
  'fullName' : string,
  'mobileNumber' : string,
  'email' : string,
}
export interface DashboardStats {
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'totalSales' : Centavos,
  'todaysSales' : Centavos,
  'completedOrders' : bigint,
}
export interface DineInDetails {
  'numberOfCustomers' : bigint,
  'tableNumber' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type FileRef = Uint8Array;
export type Id = bigint;
export interface LineCustomization {
  'sugarLevel' : [] | [string],
  'milkOption' : [] | [string],
  'addOnIds' : Array<Id>,
  'sizeId' : [] | [Id],
  'iceLevel' : [] | [string],
}
export interface Menu {
  'categories' : Array<Category>,
  'sizes' : Array<SizeOption>,
  'addOns' : Array<AddOn>,
  'products' : Array<Product>,
}
export interface Order {
  'status' : OrderStatus,
  'total' : Centavos,
  'customer' : CustomerInfo,
  'createdAt' : Timestamp,
  'orderType' : OrderType,
  'serviceFee' : Centavos,
  'takeOut' : [] | [TakeOutDetails],
  'updatedAt' : Timestamp,
  'specialInstructions' : string,
  'dineIn' : [] | [DineInDetails],
  'items' : Array<OrderItem>,
  'orderNumber' : string,
  'payment' : PaymentInfo,
  'subtotal' : Centavos,
}
export type OrderError = {
    'invalidStatusTransition' : { 'to' : OrderStatus, 'from' : OrderStatus }
  } |
  { 'notAuthorized' : null } |
  { 'unknownOrder' : string } |
  { 'invalidCustomerInfo' : string } |
  { 'productUnavailable' : Id } |
  { 'unknownProduct' : Id } |
  { 'invalidOrderType' : string } |
  { 'invalidPayment' : string } |
  { 'emptyCart' : null };
export interface OrderFilter {
  'status' : [] | [OrderStatus],
  'orderType' : [] | [OrderType],
}
export interface OrderItem {
  'lineTotal' : Centavos,
  'productId' : Id,
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : Centavos,
  'customization' : LineCustomization,
}
export type OrderStatus = { 'orderConfirmed' : null } |
  { 'readyForPickup' : null } |
  { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'orderReceived' : null } |
  { 'paymentVerification' : null };
export interface OrderSummary {
  'customerName' : string,
  'status' : OrderStatus,
  'total' : Centavos,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Timestamp,
  'orderType' : OrderType,
  'orderNumber' : string,
}
export type OrderType = { 'takeOut' : null } |
  { 'dineIn' : null };
export interface PaymentInfo {
  'method' : PaymentMethod,
  'referenceNumber' : [] | [string],
  'proof' : [] | [StoredFile],
}
export type PaymentMethod = { 'cash' : null } |
  { 'maya' : null } |
  { 'gcash' : null };
export interface PaymentSettings {
  'mayaNumber' : string,
  'gcashQr' : [] | [StoredFile],
  'gcashNumber' : string,
  'mayaQr' : [] | [StoredFile],
}
export interface PaymentSettingsInput {
  'mayaNumber' : string,
  'gcashQr' : [] | [StoredFile],
  'gcashNumber' : string,
  'mayaQr' : [] | [StoredFile],
}
export interface PlaceOrderInput {
  'customer' : CustomerInfo,
  'orderType' : OrderType,
  'takeOut' : [] | [TakeOutDetails],
  'specialInstructions' : string,
  'dineIn' : [] | [DineInDetails],
  'items' : Array<OrderItem>,
  'payment' : PaymentInfo,
}
export interface Product {
  'id' : Id,
  'categoryId' : Id,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'addOnIds' : Array<Id>,
  'sizeOptionIds' : Array<Id>,
  'image' : [] | [StoredFile],
  'price' : Centavos,
}
export interface ProductInput {
  'categoryId' : Id,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'addOnIds' : Array<Id>,
  'sizeOptionIds' : Array<Id>,
  'image' : [] | [StoredFile],
  'price' : Centavos,
}
export type Result = { 'ok' : Order } |
  { 'err' : OrderError };
export type Result_1 = { 'ok' : string } |
  { 'err' : OrderError };
export type Result_2 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface SizeOption {
  'id' : Id,
  'surcharge' : Centavos,
  'name' : string,
}
export interface SizeOptionInput { 'surcharge' : Centavos, 'name' : string }
export interface StoredFile {
  'blob' : FileRef,
  'mimeType' : string,
  'filename' : string,
}
export interface TakeOutDetails { 'pickupTime' : string }
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_2>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Admin: cancel an order.
   */
  'cancelOrder' : ActorMethod<[string], Result>,
  /**
   * / Admin: create an add-on.
   */
  'createAddOn' : ActorMethod<[AddOnInput], Id>,
  /**
   * / Admin: create a category.
   */
  'createCategory' : ActorMethod<[CategoryInput], Id>,
  /**
   * / Admin: create a product.
   */
  'createProduct' : ActorMethod<[ProductInput], Id>,
  /**
   * / Admin: create a size option.
   */
  'createSizeOption' : ActorMethod<[SizeOptionInput], Id>,
  /**
   * / Admin: delete an add-on.
   */
  'deleteAddOn' : ActorMethod<[Id], boolean>,
  /**
   * / Admin: delete a category.
   */
  'deleteCategory' : ActorMethod<[Id], boolean>,
  /**
   * / Admin: delete a product.
   */
  'deleteProduct' : ActorMethod<[Id], boolean>,
  /**
   * / Admin: delete a size option.
   */
  'deleteSizeOption' : ActorMethod<[Id], boolean>,
  'execute' : ActorMethod<[string], Result__1>,
  /**
   * / Static Markdown documentation of this backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / Resolve the caller's audience for role-aware routing.
   * /
   * / Never traps: an anonymous or not-yet-registered caller resolves to
   * / `#anonymous`, a registered customer to `#customer`, and a registered
   * / staff account to `#admin`.
   */
  'getCallerRole' : ActorMethod<[], CallerRole>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Admin: dashboard counters.
   */
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  /**
   * / Public storefront menu.
   */
  'getMenu' : ActorMethod<[], Menu>,
  /**
   * / Track an order by its order number.
   */
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  /**
   * / Public: configurable shop payment settings.
   */
  'getPaymentSettings' : ActorMethod<[], PaymentSettings>,
  /**
   * / Public product lookup.
   */
  'getProduct' : ActorMethod<[Id], [] | [Product]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Admin: list orders, optionally filtered.
   */
  'listOrders' : ActorMethod<[OrderFilter], Array<OrderSummary>>,
  /**
   * / Place an order. Open to any caller, including anonymous guests.
   */
  'placeOrder' : ActorMethod<[PlaceOrderInput], Result_1>,
  /**
   * / Register the caller as a customer account.
   * /
   * / This is the customer portal's registration path. It always assigns the
   * / `#user` role, so a customer signing in first can never claim the shop's
   * / admin account — only the staff portal's `_initialize_access_control`
   * / path can promote the first sign-in to `#admin`. Calling it again for an
   * / already-registered caller is a no-op.
   */
  'registerCustomer' : ActorMethod<[], undefined>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Admin: update an add-on.
   */
  'updateAddOn' : ActorMethod<[Id, AddOnInput], boolean>,
  /**
   * / Admin: update a category.
   */
  'updateCategory' : ActorMethod<[Id, CategoryInput], boolean>,
  /**
   * / Admin: change an order's status.
   */
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], Result>,
  /**
   * / Admin: update shop payment settings.
   */
  'updatePaymentSettings' : ActorMethod<
    [PaymentSettingsInput],
    PaymentSettings
  >,
  /**
   * / Admin: update a product.
   */
  'updateProduct' : ActorMethod<[Id, ProductInput], boolean>,
  /**
   * / Admin: update a size option.
   */
  'updateSizeOption' : ActorMethod<[Id, SizeOptionInput], boolean>,
  /**
   * / Admin: verify a GCash/Maya payment.
   */
  'verifyPayment' : ActorMethod<[string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];