/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface AddOn {
    id: Id;
    name: string;
    available: boolean;
    price: Centavos;
}
export interface AddOnInput {
    name: string;
    available: boolean;
    price: Centavos;
}
export interface Category {
    id: Id;
    sortOrder: bigint;
    name: string;
}
export interface CategoryInput {
    sortOrder: bigint;
    name: string;
}
export interface Cell {
    value: Value;
    name: string;
}
export type Centavos = bigint;
export interface CustomerInfo {
    fullName: string;
    mobileNumber: string;
    email: string;
}
export interface DashboardStats {
    totalOrders: bigint;
    pendingOrders: bigint;
    totalSales: Centavos;
    todaysSales: Centavos;
    completedOrders: bigint;
}
export interface DineInDetails {
    numberOfCustomers: bigint;
    tableNumber: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type FileRef = Uint8Array;
export type Id = bigint;
export interface LineCustomization {
    sugarLevel?: string;
    milkOption?: string;
    addOnIds: Array<Id>;
    sizeId?: Id;
    iceLevel?: string;
}
export interface Menu {
    categories: Array<Category>;
    sizes: Array<SizeOption>;
    addOns: Array<AddOn>;
    products: Array<Product>;
}
export interface Order {
    status: OrderStatus;
    total: Centavos;
    customer: CustomerInfo;
    createdAt: Timestamp;
    orderType: OrderType;
    serviceFee: Centavos;
    takeOut?: TakeOutDetails;
    updatedAt: Timestamp;
    specialInstructions: string;
    dineIn?: DineInDetails;
    items: Array<OrderItem>;
    orderNumber: string;
    payment: PaymentInfo;
    subtotal: Centavos;
}
export type OrderError = {
    __kind__: "invalidStatusTransition";
    invalidStatusTransition: {
        to: OrderStatus;
        from: OrderStatus;
    };
} | {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "unknownOrder";
    unknownOrder: string;
} | {
    __kind__: "invalidCustomerInfo";
    invalidCustomerInfo: string;
} | {
    __kind__: "productUnavailable";
    productUnavailable: Id;
} | {
    __kind__: "unknownProduct";
    unknownProduct: Id;
} | {
    __kind__: "invalidOrderType";
    invalidOrderType: string;
} | {
    __kind__: "invalidPayment";
    invalidPayment: string;
} | {
    __kind__: "emptyCart";
    emptyCart: null;
};
export interface OrderFilter {
    status?: OrderStatus;
    orderType?: OrderType;
}
export interface OrderItem {
    lineTotal: Centavos;
    productId: Id;
    productName: string;
    quantity: bigint;
    unitPrice: Centavos;
    customization: LineCustomization;
}
export interface OrderSummary {
    customerName: string;
    status: OrderStatus;
    total: Centavos;
    paymentMethod: PaymentMethod;
    createdAt: Timestamp;
    orderType: OrderType;
    orderNumber: string;
}
export interface PaymentInfo {
    method: PaymentMethod;
    referenceNumber?: string;
    proof?: StoredFile;
}
export interface PaymentSettings {
    mayaNumber: string;
    gcashQr?: StoredFile;
    gcashNumber: string;
    mayaQr?: StoredFile;
}
export interface PaymentSettingsInput {
    mayaNumber: string;
    gcashQr?: StoredFile;
    gcashNumber: string;
    mayaQr?: StoredFile;
}
export interface PlaceOrderInput {
    customer: CustomerInfo;
    orderType: OrderType;
    takeOut?: TakeOutDetails;
    specialInstructions: string;
    dineIn?: DineInDetails;
    items: Array<OrderItem>;
    payment: PaymentInfo;
}
export interface Product {
    id: Id;
    categoryId: Id;
    name: string;
    description: string;
    available: boolean;
    addOnIds: Array<Id>;
    sizeOptionIds: Array<Id>;
    image?: StoredFile;
    price: Centavos;
}
export interface ProductInput {
    categoryId: Id;
    name: string;
    description: string;
    available: boolean;
    addOnIds: Array<Id>;
    sizeOptionIds: Array<Id>;
    image?: StoredFile;
    price: Centavos;
}
export type Result = {
    __kind__: "ok";
    ok: Order;
} | {
    __kind__: "err";
    err: OrderError;
};
export type Result_1 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: OrderError;
};
export type Result_2 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface SizeOption {
    id: Id;
    surcharge: Centavos;
    name: string;
}
export interface SizeOptionInput {
    surcharge: Centavos;
    name: string;
}
export interface StoredFile {
    blob: FileRef;
    mimeType: string;
    filename: string;
}
export interface TakeOutDetails {
    pickupTime: string;
}
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum CallerRole {
    admin = "admin",
    customer = "customer",
    anonymous = "anonymous"
}
export enum OrderStatus {
    orderConfirmed = "orderConfirmed",
    readyForPickup = "readyForPickup",
    preparing = "preparing",
    cancelled = "cancelled",
    completed = "completed",
    orderReceived = "orderReceived",
    paymentVerification = "paymentVerification"
}
export enum OrderType {
    takeOut = "takeOut",
    dineIn = "dineIn"
}
export enum PaymentMethod {
    cash = "cash",
    maya = "maya",
    gcash = "gcash"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_2>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Admin: cancel an order.
     */
    cancelOrder(orderNumber: string): Promise<Result>;
    /**
     * / Admin: create an add-on.
     */
    createAddOn(input: AddOnInput): Promise<Id>;
    /**
     * / Admin: create a category.
     */
    createCategory(input: CategoryInput): Promise<Id>;
    /**
     * / Admin: create a product.
     */
    createProduct(input: ProductInput): Promise<Id>;
    /**
     * / Admin: create a size option.
     */
    createSizeOption(input: SizeOptionInput): Promise<Id>;
    /**
     * / Admin: delete an add-on.
     */
    deleteAddOn(id: Id): Promise<boolean>;
    /**
     * / Admin: delete a category.
     */
    deleteCategory(id: Id): Promise<boolean>;
    /**
     * / Admin: delete a product.
     */
    deleteProduct(id: Id): Promise<boolean>;
    /**
     * / Admin: delete a size option.
     */
    deleteSizeOption(id: Id): Promise<boolean>;
    execute(qJson: string): Promise<Result__1>;
    /**
     * / Static Markdown documentation of this backend's public API.
     */
    getApiDoc(): Promise<string>;
    /**
     * / Resolve the caller's audience for role-aware routing.
     * /
     * / Never traps: an anonymous or not-yet-registered caller resolves to
     * / `#anonymous`, a registered customer to `#customer`, and a registered
     * / staff account to `#admin`.
     */
    getCallerRole(): Promise<CallerRole>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Admin: dashboard counters.
     */
    getDashboardStats(): Promise<DashboardStats>;
    /**
     * / Public storefront menu.
     */
    getMenu(): Promise<Menu>;
    /**
     * / Track an order by its order number.
     */
    getOrder(orderNumber: string): Promise<Order | null>;
    /**
     * / Public: configurable shop payment settings.
     */
    getPaymentSettings(): Promise<PaymentSettings>;
    /**
     * / Public product lookup.
     */
    getProduct(id: Id): Promise<Product | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Admin: list orders, optionally filtered.
     */
    listOrders(filter: OrderFilter): Promise<Array<OrderSummary>>;
    /**
     * / Place an order. Open to any caller, including anonymous guests.
     */
    placeOrder(input: PlaceOrderInput): Promise<Result_1>;
    /**
     * / Register the caller as a customer account.
     * /
     * / This is the customer portal's registration path. It always assigns the
     * / `#user` role, so a customer signing in first can never claim the shop's
     * / admin account — only the staff portal's `_initialize_access_control`
     * / path can promote the first sign-in to `#admin`. Calling it again for an
     * / already-registered caller is a no-op.
     */
    registerCustomer(): Promise<void>;
    schema(): Promise<string>;
    /**
     * / Admin: update an add-on.
     */
    updateAddOn(id: Id, input: AddOnInput): Promise<boolean>;
    /**
     * / Admin: update a category.
     */
    updateCategory(id: Id, input: CategoryInput): Promise<boolean>;
    /**
     * / Admin: change an order's status.
     */
    updateOrderStatus(orderNumber: string, status: OrderStatus): Promise<Result>;
    /**
     * / Admin: update shop payment settings.
     */
    updatePaymentSettings(input: PaymentSettingsInput): Promise<PaymentSettings>;
    /**
     * / Admin: update a product.
     */
    updateProduct(id: Id, input: ProductInput): Promise<boolean>;
    /**
     * / Admin: update a size option.
     */
    updateSizeOption(id: Id, input: SizeOptionInput): Promise<boolean>;
    /**
     * / Admin: verify a GCash/Maya payment.
     */
    verifyPayment(orderNumber: string): Promise<Result>;
}
import type { AddOn as _AddOn, CallerRole as _CallerRole, Category as _Category, Cell as _Cell, Centavos as _Centavos, CustomerInfo as _CustomerInfo, DineInDetails as _DineInDetails, Error as _Error, Id as _Id, LineCustomization as _LineCustomization, Menu as _Menu, Order as _Order, OrderError as _OrderError, OrderFilter as _OrderFilter, OrderItem as _OrderItem, OrderStatus as _OrderStatus, OrderSummary as _OrderSummary, OrderType as _OrderType, PaymentInfo as _PaymentInfo, PaymentMethod as _PaymentMethod, PaymentSettings as _PaymentSettings, PaymentSettingsInput as _PaymentSettingsInput, PlaceOrderInput as _PlaceOrderInput, Product as _Product, ProductInput as _ProductInput, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result__1 as _Result__1, SizeOption as _SizeOption, StoredFile as _StoredFile, TakeOutDetails as _TakeOutDetails, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_2_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_2_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelOrder(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0);
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0);
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createAddOn(arg0: AddOnInput): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createAddOn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAddOn(arg0);
            return result;
        }
    }
    async createCategory(arg0: CategoryInput): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0);
            return result;
        }
    }
    async createProduct(arg0: ProductInput): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_ProductInput_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_ProductInput_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSizeOption(arg0: SizeOptionInput): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createSizeOption(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSizeOption(arg0);
            return result;
        }
    }
    async deleteAddOn(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAddOn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAddOn(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteSizeOption(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSizeOption(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSizeOption(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerRole(): Promise<CallerRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRole();
                return from_candid_CallerRole_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRole();
            return from_candid_CallerRole_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMenu(): Promise<Menu> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenu();
                return from_candid_Menu_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenu();
            return from_candid_Menu_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentSettings(): Promise<PaymentSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentSettings();
                return from_candid_PaymentSettings_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentSettings();
            return from_candid_PaymentSettings_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: Id): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listOrders(arg0: OrderFilter): Promise<Array<OrderSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrders(to_candid_OrderFilter_n56(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrders(to_candid_OrderFilter_n56(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: PlaceOrderInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_PlaceOrderInput_n63(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_PlaceOrderInput_n63(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerCustomer(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCustomer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCustomer();
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async updateAddOn(arg0: Id, arg1: AddOnInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAddOn(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAddOn(arg0, arg1);
            return result;
        }
    }
    async updateCategory(arg0: Id, arg1: CategoryInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1);
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n58(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n58(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePaymentSettings(arg0: PaymentSettingsInput): Promise<PaymentSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentSettings(to_candid_PaymentSettingsInput_n75(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PaymentSettings_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentSettings(to_candid_PaymentSettingsInput_n75(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PaymentSettings_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: Id, arg1: ProductInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n35(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n35(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSizeOption(arg0: Id, arg1: SizeOptionInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSizeOption(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSizeOption(arg0, arg1);
            return result;
        }
    }
    async verifyPayment(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPayment(arg0);
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPayment(arg0);
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CallerRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallerRole): CallerRole {
    return "admin" in value ? CallerRole.admin : "customer" in value ? CallerRole.customer : "anonymous" in value ? CallerRole.anonymous : value;
}
function from_candid_Cell_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_LineCustomization_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LineCustomization): LineCustomization {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Menu_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Menu): Menu {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_OrderError_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderError): OrderError {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_OrderItem_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderItem): OrderItem {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return "orderConfirmed" in value ? OrderStatus.orderConfirmed : "readyForPickup" in value ? OrderStatus.readyForPickup : "preparing" in value ? OrderStatus.preparing : "cancelled" in value ? OrderStatus.cancelled : "completed" in value ? OrderStatus.completed : "orderReceived" in value ? OrderStatus.orderReceived : "paymentVerification" in value ? OrderStatus.paymentVerification : value;
}
function from_candid_OrderSummary_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderSummary): OrderSummary {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return "takeOut" in value ? OrderType.takeOut : "dineIn" in value ? OrderType.dineIn : value;
}
function from_candid_Order_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentInfo_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentInfo): PaymentInfo {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return "cash" in value ? PaymentMethod.cash : "maya" in value ? PaymentMethod.maya : "gcash" in value ? PaymentMethod.gcash : value;
}
function from_candid_PaymentSettings_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentSettings): PaymentSettings {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TakeOutDetails]): TakeOutDetails | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DineInDetails]): DineInDetails | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Id]): Id | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StoredFile]): StoredFile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrderStatus;
    total: _Centavos;
    customer: _CustomerInfo;
    createdAt: _Timestamp;
    orderType: _OrderType;
    serviceFee: _Centavos;
    takeOut: [] | [_TakeOutDetails];
    updatedAt: _Timestamp;
    specialInstructions: string;
    dineIn: [] | [_DineInDetails];
    items: Array<_OrderItem>;
    orderNumber: string;
    payment: _PaymentInfo;
    subtotal: _Centavos;
}): {
    status: OrderStatus;
    total: Centavos;
    customer: CustomerInfo;
    createdAt: Timestamp;
    orderType: OrderType;
    serviceFee: Centavos;
    takeOut?: TakeOutDetails;
    updatedAt: Timestamp;
    specialInstructions: string;
    dineIn?: DineInDetails;
    items: Array<OrderItem>;
    orderNumber: string;
    payment: PaymentInfo;
    subtotal: Centavos;
} {
    return {
        status: from_candid_OrderStatus_n17(_uploadFile, _downloadFile, value.status),
        total: value.total,
        customer: value.customer,
        createdAt: value.createdAt,
        orderType: from_candid_OrderType_n18(_uploadFile, _downloadFile, value.orderType),
        serviceFee: value.serviceFee,
        takeOut: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.takeOut)),
        updatedAt: value.updatedAt,
        specialInstructions: value.specialInstructions,
        dineIn: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.dineIn)),
        items: from_candid_vec_n21(_uploadFile, _downloadFile, value.items),
        orderNumber: value.orderNumber,
        payment: from_candid_PaymentInfo_n28(_uploadFile, _downloadFile, value.payment),
        subtotal: value.subtotal
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lineTotal: _Centavos;
    productId: _Id;
    productName: string;
    quantity: bigint;
    unitPrice: _Centavos;
    customization: _LineCustomization;
}): {
    lineTotal: Centavos;
    productId: Id;
    productName: string;
    quantity: bigint;
    unitPrice: Centavos;
    customization: LineCustomization;
} {
    return {
        lineTotal: value.lineTotal,
        productId: value.productId,
        productName: value.productName,
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        customization: from_candid_LineCustomization_n24(_uploadFile, _downloadFile, value.customization)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sugarLevel: [] | [string];
    milkOption: [] | [string];
    addOnIds: Array<_Id>;
    sizeId: [] | [_Id];
    iceLevel: [] | [string];
}): {
    sugarLevel?: string;
    milkOption?: string;
    addOnIds: Array<Id>;
    sizeId?: Id;
    iceLevel?: string;
} {
    return {
        sugarLevel: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.sugarLevel)),
        milkOption: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.milkOption)),
        addOnIds: value.addOnIds,
        sizeId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.sizeId)),
        iceLevel: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.iceLevel))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: _PaymentMethod;
    referenceNumber: [] | [string];
    proof: [] | [_StoredFile];
}): {
    method: PaymentMethod;
    referenceNumber?: string;
    proof?: StoredFile;
} {
    return {
        method: from_candid_PaymentMethod_n30(_uploadFile, _downloadFile, value.method),
        referenceNumber: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.referenceNumber)),
        proof: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.proof))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: _OrderStatus;
    from: _OrderStatus;
}): {
    to: OrderStatus;
    from: OrderStatus;
} {
    return {
        to: from_candid_OrderStatus_n17(_uploadFile, _downloadFile, value.to),
        from: from_candid_OrderStatus_n17(_uploadFile, _downloadFile, value.from)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n39(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n43(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categories: Array<_Category>;
    sizes: Array<_SizeOption>;
    addOns: Array<_AddOn>;
    products: Array<_Product>;
}): {
    categories: Array<Category>;
    sizes: Array<SizeOption>;
    addOns: Array<AddOn>;
    products: Array<Product>;
} {
    return {
        categories: value.categories,
        sizes: value.sizes,
        addOns: value.addOns,
        products: from_candid_vec_n49(_uploadFile, _downloadFile, value.products)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    categoryId: _Id;
    name: string;
    description: string;
    available: boolean;
    addOnIds: Array<_Id>;
    sizeOptionIds: Array<_Id>;
    image: [] | [_StoredFile];
    price: _Centavos;
}): {
    id: Id;
    categoryId: Id;
    name: string;
    description: string;
    available: boolean;
    addOnIds: Array<Id>;
    sizeOptionIds: Array<Id>;
    image?: StoredFile;
    price: Centavos;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        name: value.name,
        description: value.description,
        available: value.available,
        addOnIds: value.addOnIds,
        sizeOptionIds: value.sizeOptionIds,
        image: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.image)),
        price: value.price
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mayaNumber: string;
    gcashQr: [] | [_StoredFile];
    gcashNumber: string;
    mayaQr: [] | [_StoredFile];
}): {
    mayaNumber: string;
    gcashQr?: StoredFile;
    gcashNumber: string;
    mayaQr?: StoredFile;
} {
    return {
        mayaNumber: value.mayaNumber,
        gcashQr: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.gcashQr)),
        gcashNumber: value.gcashNumber,
        mayaQr: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.mayaQr))
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: _OrderStatus;
    total: _Centavos;
    paymentMethod: _PaymentMethod;
    createdAt: _Timestamp;
    orderType: _OrderType;
    orderNumber: string;
}): {
    customerName: string;
    status: OrderStatus;
    total: Centavos;
    paymentMethod: PaymentMethod;
    createdAt: Timestamp;
    orderType: OrderType;
    orderNumber: string;
} {
    return {
        customerName: value.customerName,
        status: from_candid_OrderStatus_n17(_uploadFile, _downloadFile, value.status),
        total: value.total,
        paymentMethod: from_candid_PaymentMethod_n30(_uploadFile, _downloadFile, value.paymentMethod),
        createdAt: value.createdAt,
        orderType: from_candid_OrderType_n18(_uploadFile, _downloadFile, value.orderType),
        orderNumber: value.orderNumber
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Order;
} | {
    err: _OrderError;
}): {
    __kind__: "ok";
    ok: Order;
} | {
    __kind__: "err";
    err: OrderError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Order_n15(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_OrderError_n32(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidStatusTransition: {
        to: _OrderStatus;
        from: _OrderStatus;
    };
} | {
    notAuthorized: null;
} | {
    unknownOrder: string;
} | {
    invalidCustomerInfo: string;
} | {
    productUnavailable: _Id;
} | {
    unknownProduct: _Id;
} | {
    invalidOrderType: string;
} | {
    invalidPayment: string;
} | {
    emptyCart: null;
}): {
    __kind__: "invalidStatusTransition";
    invalidStatusTransition: {
        to: OrderStatus;
        from: OrderStatus;
    };
} | {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "unknownOrder";
    unknownOrder: string;
} | {
    __kind__: "invalidCustomerInfo";
    invalidCustomerInfo: string;
} | {
    __kind__: "productUnavailable";
    productUnavailable: Id;
} | {
    __kind__: "unknownProduct";
    unknownProduct: Id;
} | {
    __kind__: "invalidOrderType";
    invalidOrderType: string;
} | {
    __kind__: "invalidPayment";
    invalidPayment: string;
} | {
    __kind__: "emptyCart";
    emptyCart: null;
} {
    return "invalidStatusTransition" in value ? {
        __kind__: "invalidStatusTransition",
        invalidStatusTransition: from_candid_record_n34(_uploadFile, _downloadFile, value.invalidStatusTransition)
    } : "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : "unknownOrder" in value ? {
        __kind__: "unknownOrder",
        unknownOrder: value.unknownOrder
    } : "invalidCustomerInfo" in value ? {
        __kind__: "invalidCustomerInfo",
        invalidCustomerInfo: value.invalidCustomerInfo
    } : "productUnavailable" in value ? {
        __kind__: "productUnavailable",
        productUnavailable: value.productUnavailable
    } : "unknownProduct" in value ? {
        __kind__: "unknownProduct",
        unknownProduct: value.unknownProduct
    } : "invalidOrderType" in value ? {
        __kind__: "invalidOrderType",
        invalidOrderType: value.invalidOrderType
    } : "invalidPayment" in value ? {
        __kind__: "invalidPayment",
        invalidPayment: value.invalidPayment
    } : "emptyCart" in value ? {
        __kind__: "emptyCart",
        emptyCart: value.emptyCart
    } : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: _OrderError;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: OrderError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_OrderError_n32(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderItem>): Array<OrderItem> {
    return value.map((x)=>from_candid_OrderItem_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderSummary>): Array<OrderSummary> {
    return value.map((x)=>from_candid_OrderSummary_n61(_uploadFile, _downloadFile, x));
}
function to_candid_LineCustomization_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LineCustomization): _LineCustomization {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_OrderFilter_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderFilter): _OrderFilter {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_OrderItem_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderItem): _OrderItem {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return value == OrderStatus.orderConfirmed ? {
        orderConfirmed: null
    } : value == OrderStatus.readyForPickup ? {
        readyForPickup: null
    } : value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.orderReceived ? {
        orderReceived: null
    } : value == OrderStatus.paymentVerification ? {
        paymentVerification: null
    } : value;
}
function to_candid_OrderType_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): _OrderType {
    return value == OrderType.takeOut ? {
        takeOut: null
    } : value == OrderType.dineIn ? {
        dineIn: null
    } : value;
}
function to_candid_PaymentInfo_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentInfo): _PaymentInfo {
    return to_candid_record_n71(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.maya ? {
        maya: null
    } : value == PaymentMethod.gcash ? {
        gcash: null
    } : value;
}
function to_candid_PaymentSettingsInput_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentSettingsInput): _PaymentSettingsInput {
    return to_candid_record_n76(_uploadFile, _downloadFile, value);
}
function to_candid_PlaceOrderInput_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceOrderInput): _PlaceOrderInput {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_ProductInput_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): _ProductInput {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId: Id;
    name: string;
    description: string;
    available: boolean;
    addOnIds: Array<Id>;
    sizeOptionIds: Array<Id>;
    image?: StoredFile;
    price: Centavos;
}): {
    categoryId: _Id;
    name: string;
    description: string;
    available: boolean;
    addOnIds: Array<_Id>;
    sizeOptionIds: Array<_Id>;
    image: [] | [_StoredFile];
    price: _Centavos;
} {
    return {
        categoryId: value.categoryId,
        name: value.name,
        description: value.description,
        available: value.available,
        addOnIds: value.addOnIds,
        sizeOptionIds: value.sizeOptionIds,
        image: value.image ? candid_some(value.image) : candid_none(),
        price: value.price
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: OrderStatus;
    orderType?: OrderType;
}): {
    status: [] | [_OrderStatus];
    orderType: [] | [_OrderType];
} {
    return {
        status: value.status ? candid_some(to_candid_OrderStatus_n58(_uploadFile, _downloadFile, value.status)) : candid_none(),
        orderType: value.orderType ? candid_some(to_candid_OrderType_n59(_uploadFile, _downloadFile, value.orderType)) : candid_none()
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: CustomerInfo;
    orderType: OrderType;
    takeOut?: TakeOutDetails;
    specialInstructions: string;
    dineIn?: DineInDetails;
    items: Array<OrderItem>;
    payment: PaymentInfo;
}): {
    customer: _CustomerInfo;
    orderType: _OrderType;
    takeOut: [] | [_TakeOutDetails];
    specialInstructions: string;
    dineIn: [] | [_DineInDetails];
    items: Array<_OrderItem>;
    payment: _PaymentInfo;
} {
    return {
        customer: value.customer,
        orderType: to_candid_OrderType_n59(_uploadFile, _downloadFile, value.orderType),
        takeOut: value.takeOut ? candid_some(value.takeOut) : candid_none(),
        specialInstructions: value.specialInstructions,
        dineIn: value.dineIn ? candid_some(value.dineIn) : candid_none(),
        items: to_candid_vec_n65(_uploadFile, _downloadFile, value.items),
        payment: to_candid_PaymentInfo_n70(_uploadFile, _downloadFile, value.payment)
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lineTotal: Centavos;
    productId: Id;
    productName: string;
    quantity: bigint;
    unitPrice: Centavos;
    customization: LineCustomization;
}): {
    lineTotal: _Centavos;
    productId: _Id;
    productName: string;
    quantity: bigint;
    unitPrice: _Centavos;
    customization: _LineCustomization;
} {
    return {
        lineTotal: value.lineTotal,
        productId: value.productId,
        productName: value.productName,
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        customization: to_candid_LineCustomization_n68(_uploadFile, _downloadFile, value.customization)
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sugarLevel?: string;
    milkOption?: string;
    addOnIds: Array<Id>;
    sizeId?: Id;
    iceLevel?: string;
}): {
    sugarLevel: [] | [string];
    milkOption: [] | [string];
    addOnIds: Array<_Id>;
    sizeId: [] | [_Id];
    iceLevel: [] | [string];
} {
    return {
        sugarLevel: value.sugarLevel ? candid_some(value.sugarLevel) : candid_none(),
        milkOption: value.milkOption ? candid_some(value.milkOption) : candid_none(),
        addOnIds: value.addOnIds,
        sizeId: value.sizeId ? candid_some(value.sizeId) : candid_none(),
        iceLevel: value.iceLevel ? candid_some(value.iceLevel) : candid_none()
    };
}
function to_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: PaymentMethod;
    referenceNumber?: string;
    proof?: StoredFile;
}): {
    method: _PaymentMethod;
    referenceNumber: [] | [string];
    proof: [] | [_StoredFile];
} {
    return {
        method: to_candid_PaymentMethod_n72(_uploadFile, _downloadFile, value.method),
        referenceNumber: value.referenceNumber ? candid_some(value.referenceNumber) : candid_none(),
        proof: value.proof ? candid_some(value.proof) : candid_none()
    };
}
function to_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mayaNumber: string;
    gcashQr?: StoredFile;
    gcashNumber: string;
    mayaQr?: StoredFile;
}): {
    mayaNumber: string;
    gcashQr: [] | [_StoredFile];
    gcashNumber: string;
    mayaQr: [] | [_StoredFile];
} {
    return {
        mayaNumber: value.mayaNumber,
        gcashQr: value.gcashQr ? candid_some(value.gcashQr) : candid_none(),
        gcashNumber: value.gcashNumber,
        mayaQr: value.mayaQr ? candid_some(value.mayaQr) : candid_none()
    };
}
function to_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OrderItem>): Array<_OrderItem> {
    return value.map((x)=>to_candid_OrderItem_n66(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
